apiVersion: v1
kind: Service
metadata:
  namespace: quotes
  labels:
    app: mongodb-service
  name: mongodb-service
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30010
  selector:
    service: mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: quotes
  name: mongodb-service
  labels:
    service: mongodb-service
spec:
  selector:
    matchLabels:
      service: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        service: mongodb-service
      name: mongodb-service
    spec:
      containers:
      - image: mongo:latest
        name: mongodb-service
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password