Now we know what Kubernetes is, how it does it's thing, and why we want to use it, let's actually use it.

I've created several applications, which you can find in the `pracical` folder. I've also introduced several checkpoints, which you can find in corresponding `step` folders.

The rough outline is that we will start off with a docker compose file, and transition to Kubernetes. For this I'll use kompose, a tool provided by Kubernetes to move from `docker-compose` into Kubernetes files. You can find more information about it here: https://github.com/kubernetes/kompose

After that, I'll give you a quick runthrough multiple options you have when working with Kubernetes. The applications are small applications, which are supposed to introduce you to a single concept. The last app is a small application which depends on a database, and is a bit more towards what an actual application would look like.

The following apps are in the `partical` folder:

* environment-variable-app - Introducing a simple deployment.
* config-map-app - Introducing config maps.
* quotes-app - A small application which loads some quotes from the database, and displays these quotes whenever asked.

### environment-variable-app

This application is a rather simple app. It exposes two endpoints which we can use our browser to hit. One being `/message` and another being `/services`. The first reads an environment variable named `APP_ENV_VAR` and simply outputs it. The latter is a bit more complicated. It will read all the services it's able to detect from the Kubernetes API, and outputs them. Small note here, I apologize for the formatting. There's no clean split between all the services names, but I'm sure you'll get the gist.

### config-map-app

This application is almost a copy of the previous. However, instead of reading from an environment variable, it reads from an properties file. This is baked into the application, however, with the power of Kubernetes config maps we will push new configuration into the application, and it'll pick up a new message, refreshing the old one.

### quotes-app

This is a "real life" application which retrieves some information from a database, also deployed, and offers that through an API. 

### Sample setup
include::sample-setup.adoc[]

### Kompose
include::kompose.adoc[]

### Config Maps
include::config-maps.adoc[]

### Secrets

We've talked about config maps, which should be used for non-sensitive information. However, when deploying a database with a password, that's pretty sensitive. 

Secrets help out in this use case. 

For this example, I'll be deploying a MongoDB container, and link an application to it. I'll have a secret in the deployment, which would be used by both the database to configure itself, and the application to create a connection to the database.

Let's see the definition of the secret we will be using.

[NOTE]
====
The username and password are both 'admin' in this case. Feel free to connect to the database on `localhost:30010`.
====

```
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  username: YWRtaW4=
  password: YWRtaW4=
```

Let's apply it by running: `kubectl apply -f database-secret`

There is not much to mention here. It's really straight forward. Now, let's look at how the MongoDB deployment utilizes this.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-service
  labels:
    service: mongodb-service
spec:
  selector:
    matchLabels:
      service: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        service: mongodb-service
      name: mongodb-service
    spec:
      containers:
      - image: mongo:latest
        name: mongodb-service
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
```
The most interesting part here is the `env` key. These are required to setup the database. However, both of these variables are references to the secret, by name, and the key you'd want the value from. This is then supplied to the database, and will be able to logged onto. 

Let's apply this, and check the logs. `kubectl apply -f mongodb-deployment.yml`, then `kubectl get pod`, and simply `kubectl logs POD_NAME`. If we scroll up through the logs a bit, we will see something like the following:

```
Successfully added user: {
        "user" : "admin",
        "roles" : [
                {
                        "role" : "root",
                        "db" : "admin"
                }
        ]
}
```

We've created a user with username `admin` and password `admin`.

Finally, we have a sample application which retrieves that information. Let's just apply the deployment, and check what quotes we can retrieve! 

`kubectl apply -f quotes-app-deployment.yml`

### Scaling deployments

Now we've got a running application. Imagine we would want to scale the application giving us these quotes, because the demand for quotes is through the roof!

Usually scaling is pretty tough when you are running on a virtual machine, or even on an actual host. You'd have to usually buy some more hardware. While our laptop probably will not be able to scale up significantly, cloud providers take that away from us. Also, the time to scale with the previously mentioned mechanisms are time intensive.

Let's see how Kubernetes handles such a request.

`kubectl scale --replicas=5 deployment quotes-app`

After querying the cluster for all its resources, you can see the following output, ish:

```
joran@DESKTOP-8V8KV4D MINGW64 ~/VCS/KNMI/k8s-kiss/practical (master)
$ k get all
NAME                                   READY   STATUS    RESTARTS   AGE
pod/mongodb-service-55b5bc5bfc-fbdq8   1/1     Running   0          18m
pod/quotes-app-8479bf7dd4-5vzl4        1/1     Running   0          6s
pod/quotes-app-8479bf7dd4-5xm47        1/1     Running   0          6s
pod/quotes-app-8479bf7dd4-68cbb        1/1     Running   0          6s
pod/quotes-app-8479bf7dd4-dcvfc        1/1     Running   0          17m
pod/quotes-app-8479bf7dd4-gx7h9        1/1     Running   0          6s

NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
service/kubernetes           ClusterIP   10.96.0.1        <none>        443/TCP           45d
service/mongodb-service      NodePort    10.110.62.245    <none>        27017:30010/TCP   18m
service/quotes-app-service   NodePort    10.104.248.108   <none>        8080:30003/TCP    18m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mongodb-service   1/1     1            1           18m
deployment.apps/quotes-app        5/5     5            5           17m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/mongodb-service-55b5bc5bfc   1         1         1       18m
replicaset.apps/quotes-app-8479bf7dd4        5         5         5       17m
```

So in a manner of seconds, we have added another four pods, each with the application in it. The process of downscaling is just as simple by executing `kubectl scale --replicas=1 deployment quotes-app`

### Autoscaling

While not easily possible for the local installation, I thought it would be worth looking at Autoscaling as well. I recommend reading this blog post: https://kubernetes.io/blog/2016/07/autoscaling-in-kubernetes/ 

As part of the AWS cluster script, it also installs the metrics server. So, if you have your kubectl context setup for EKS, you can follow along. 

Let's create a deployment based on example provided in the blog.

```
kubectl run php-apache --image=gcr.io/google_containers/hpa-example --requests=cpu=500m,memory=500M --expose --port=80
```

While inspecting this deployment, we just see a single deployment and pod. Let's configure this deployment to scale automatically, depending on the load. 

```
kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10

```
We could of course do this through yaml as well.

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```

Let's quickly check what the status of the autoscaler is. We can do this through `kubectl get hpa`.

To generate some load for the deployment, open a command prompt, and run the following.

```
kubectl run busybox --image=busybox:latest --rm -it --restart=Never
while true; do wget -q -O- http://php-apache.default.svc.cluster.local; done
```
